sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
  - "$HOME/.yarn-cache"
jobs:
  include:
  - stage: e2e
    script:
    - cypress run